### ISSUE TITLE
Why does this repository exist?

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/mathcad#1]
There was previously a repository named mathcad, just like this one. I renamed it to mathcad_Final_Designs to make it more descriptive. It is [located here](https://github.com/AguaClara/mathcad_Final_Designs).

At the moment I don't see a reason to keep both of these repositories, but I don't know why this repository was created and I don't know how to see who made it to ask them directly.

To you people watching this repo- do any of you know why this repo exists? If the creator reads this, can you explain why this is here?

@monroews or @clare45 may also know

**Comment by monroews** [comment]
Ethan is in the process of creating a full repository. I don't know the status of that effort. Once that effort is complete we won't need any of these single version snapshot  repositories.
