### ISSUE TITLE
Cornell Sourceforge Deactivation Impacting this repo

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/mathcad#2]
Heyo @ethan92429 ,

Do you know if the deactivation of Cornell's sourceforge will impact this method of reverting to previous versions of the design tool?

Will the `git log --all --grep='design@4921'` command still work once teamforge is decomissioned?

Thank you so much for getting this to work in the first place! 🥇

**Comment by eak24** [comment]
This repo has no live connection to sourceforge. I is entirely a git repo now. So it won't de impacted. Please make sure it works for you!
