### ISSUE TITLE
File Format is for Mathcad Prime 4, not Mathcad 15

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/mathcad#3]
@ethan92429 

I don't know if this was intentional, but the file format for every Mathcad document in this repo is .mcdx, which is the file extension for Mathcad Prime 4. This file extension can't be read by Mathcad 15, and therefore no .mcdx file can be used as a reference in a .xmcd file.  Rather problematic!

Is there a way to port the svn sourceforge info _without_ having to convert to .mcdx? A quick search online reveals that PTC is the worst company ever and [there does not appear to be a way to convert from .mcdx to .xmcd](https://community.ptc.com/t5/PTC-Mathcad-Questions/mcdx-to-xmcd/td-p/248269). In my attempt to find a converter, some cruel soul left this:

![image](https://user-images.githubusercontent.com/27255695/45378372-7ec22f80-b5ba-11e8-818c-63ea4a8d720f.png)

How can we solve this problem?

**Comment by eak24** [comment]
All the final designs are in [xmcd...](https://github.com/AguaClara/mathcad/tree/master/Final%20Designs) I must be missing something @juanchon998

**Comment by juanchon998** [comment]
I was looking in the wrong place... Thank goodness!!!!! Everything is ok, I reacted too quickly 😅
