### ISSUE TITLE
`git pull` does not return to current branch/state

### ISSUE THREAD

**Issue by juanchon998** [AguaClara/mathcad#4]
Specified in the readme is that `git pull` returns ones local files to their initial state after having checked out a previous commit. This does not work for me. Instead, `git checkout master` gets me back on the base branch. 
![image](https://user-images.githubusercontent.com/27255695/45557182-41e47b80-b7fa-11e8-8d2d-9c3a79bd76ec.png)

This is not very consequential, but is worth noting.

Other that that, this works, great job @ethan92429 🏆

**Comment by eak24** [comment]
This appears to be a mac v. windows default setting error. Indeed, git checkout master is a better way to go about it. @juanchon998 wanna update the readme?

**Comment by juanchon998** [comment]
Donezo
